default:
	@g++ -Wall -std=c++11 main.cpp -std=c++11 include/Piece.cpp include/Rook.cpp include/Bishop.cpp include/Knight.cpp include/Pawn.cpp include/Queen.cpp include/King.cpp include/MoveNode.cpp include/State.cpp include/Gameboard.cpp -lsfml-graphics -lsfml-window -lsfml-system -o chess.out
	@./chess.out
